### PR TITLE
feat(schematic): modified docker image when running schematic APIs with uWSGI

### PR DESCRIPTION
**Pull request by linglp**
Related to: https://sagebionetworks.jira.com/browse/FDS-1346

## Context
The goal of this PR is to make sure schematic can work well with uWSGI. 

Even though a lot of content in this docker image would need to get changed when adding nginx, I still want to make a PR to make sure that we have `schematic+uwsgi` working if there's anything wrong with nginx and we want to trouble shoot by isolating uswgi and nginx. 

## Changelog
* Thomas already have uswgi working with schematic APIs. To make sure that all the endpoints work properly, I modified permission of some folders. I previously did it like this PR: https://github.com/Sage-Bionetworks/schematic/pull/1142/files#diff-d04806eafd231d6405de22d8c29951c269796bcea02a3fc8116c48f33e96ac6d but I think the way that i have now is clearer. 
* I updated the uswgi.ini so that it looks like our current set up in schematic. 

## Test
Get into the right dir
```
cd apps/schematic/api
```
Build a docker image: 
```
docker build -t schematic_api .
```
Run docker container: 
```
docker run -p 7080:7080 schematic_api
```
Should then be able to visit `http://localhost:7080/api/v1/ui/#/`
I tested all the endpoints and make sure that they could return expected output.

### CODE REVIEW

**Comment by tschaffter** [comment]
uSWGI => uWSGI

**Comment by tschaffter** [comment]
Thanks for providing the steps to test this PR! 💪 It's preferred to document the step using the monorepo API to benefit from the features that the monorepo management tool Nx provides like caching, running tasks for dependent projects, etc.

For example:

Build the image of Schematic API:

```
nx build-image schematic-api
```

> **Note**
> No need to step into the project folder.

 Start Schematic API with Docker:

```
nx serve-detach schematic-api
```

**Comment by tschaffter** [comment]
It's also preferred to not include commits that have nothing to do with this PR (here the first 12 commits). To avoid this in the future:

1. Update your remote `upstream` (official repo)

```
git fetch upstream
```

2. Create a feature branch from `upstream/main`

```
git checkout -b upstream/main
```

Alternatively, you can maintain your fork's `main` branch as a mirror of `upstream/main`, then start your feature branch from your fork's `main` branch. To update your fork's `main` branch:

```
git fetch upstream
git checkout main
git rebase upstream/main
# always work in a feature branch, i.e. never add manually commits to your fork's `main` branch with `git commit ...`.
```

You can still clean up this PR by rebasing your feature branch with `upstream/main`, then force-push the changes to your fork's feature branch.

```
git fetch upstream
git checkout develop-schematic-container
git rebase upstream/main
git push -f
```

**Comment by linglp** [comment]
@tschaffter Thanks for your comment Thomas. To make sure that my dev environment will work and this PR is up to date with changes in `upstream/main`, I made sure that the main branch in my fork is update to date with the main in upstream and then re-created a branch from my main. Let me close this PR for now

**Pull request closed without merging**
