### PR TITLE
feat(angular): Implement `ChallengeContributionsService` to get contributions in Challenge Profile pagfe

### PR DESCRIPTION
**Pull request by rrchai**
- Update the client to use `ChallengeContributionsService `
- Get the contributions on the Challenge Profile > Contributions using `ChallengeContributionsService`

### Blocked

In order to get the orgs using `getOrganization()`, the contribution(org)'s `login` is required, which is not returned by current `ChallengeContributionsService` (only returning `organizationId`).

### Depends on:
- [ ] update `ChallengeContributionsService` to return contribution(org)'s login, or enable the `OrganizationService` to use `organizationId` to get the org.
- [ ] #1666

### CODE REVIEW

**Comment by tschaffter** [comment]
> Update the client to use ChallengeContributionsService 

@rrchai This is done in #1667

**Comment by rrchai** [comment]
@tschaffter Cool! I will update this pr when we're back to add challenges' contributions in the frontend.

**Comment by tschaffter** [comment]
@rrchai That was not my intention to close this PR. It seems that removing the branch `Sage-Bionetworks:challenge-contributions` after I merged it automatically closed this PR.

**Comment by rrchai** [comment]
FYI: @tschaffter  here is the ticket - update Org service to get Org by Id, but feel free to open a fresh one.

**Pull request closed without merging**
