### PR TITLE
feat: Create unit test for the image service

### LINKED ISSUE #1456: [Story] Write a unit test for the enpoint of the image service
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want a reproducible way to test the implementation of a microservice so that I and the CI workflow can run the tests easily.

### Description

The goal of this story is to write unit tests for the single endpoint of the image service. This service is a good candidate for starting to write unit test because it has no dependency (e.g. DBs). Technically, the service does not even need Thumbor to run to work, though Thumbor is currently deployed as a dependency of the image service.

### Acceptance criteria

- The unit tests can be run with `nx test openchallenges-image-service`.
- The above command is successful.

### Tasks

- [x] Add the definition of the `test` task to the image service
  - See the `auth-service` file `project.json` for an example
- [x] Update the file `build.gradle` to support unit and integration tests
  - See this [example](https://github.com/Sage-Bionetworks/sage-monorepo/blob/515db23f619b1a52780a75b5387a5cd01af2c2e0/apps/openchallenges/user-service/build.gradle.old#L24-L48) may be useful (look for references to "test" in the entire file)
- [x] Create a unit test file to test the endpoint of the image service
  - See this [example](https://github.com/Sage-Bionetworks/sage-monorepo/tree/515db23f619b1a52780a75b5387a5cd01af2c2e0/apps/openchallenges/user-service/src.old)

### Anything else?

Searching for Medium or Baeldung articles on how to write unit and integration test for Sprint boot service could help. I believe that the standard is now to use JUnit 5 (ignore JUnit 4 solution as I believe quite a few things have changed since).

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### PR DESCRIPTION
**Pull request by mdsage1**
Fixes #1456

## Changelog

- Setup unit test for the image service
- Add one unit test for the image service
- Modify the ImageService constructor to inject an instance of `Thumbor`
- Add a Mockito plugin to enable mocking `final` objects
- Running the unit tests will not attempt to access the config server. Instead, config data are read from `test/resources/application.yml`.

## Preview

Run `nx test openchallenges-image-service` or `./gradlew test`, the latter from the project folder.

```console
vscode@0fb43fed7afd:/workspaces/sage-monorepo/apps/openchallenges/image-service$ ./gradlew test

> Task :test

ImageServiceApplicationTests STANDARD_OUT
    04:07:32.638 [Test worker] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
    04:07:32.648 [Test worker] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
    04:07:32.684 [Test worker] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
    04:07:32.698 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Neither @ContextConfiguration nor @ContextHierarchy found for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests], using SpringBootContextLoader
    04:07:32.702 [Test worker] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]: class path resource [org/sagebionetworks/openchallenges/image/service/ImageServiceApplicationTests-context.xml] does not exist
    04:07:32.703 [Test worker] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]: class path resource [org/sagebionetworks/openchallenges/image/service/ImageServiceApplicationTestsContext.groovy] does not exist
    04:07:32.704 [Test worker] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]: no resource found for suffixes {-context.xml, Context.groovy}.
    04:07:32.704 [Test worker] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils - Could not detect default configuration classes for test class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]: ImageServiceApplicationTests does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
    04:07:32.742 [Test worker] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]
    04:07:32.792 [Test worker] DEBUG org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider - Identified candidate component class: file [/workspaces/sage-monorepo/apps/openchallenges/image-service/build/classes/java/main/org/sagebionetworks/openchallenges/image/service/ImageServiceApplication.class]
    04:07:32.793 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Found @SpringBootConfiguration org.sagebionetworks.openchallenges.image.service.ImageServiceApplication for test class org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests
    04:07:32.902 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - @TestExecutionListeners is not present for class [org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests]: using defaults.
    04:07:32.902 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
    04:07:32.911 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Skipping candidate TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestExecutionListener] due to a missing dependency. Specify custom listener classes or make the default listener classes and their required dependencies available. Offending class: [org/springframework/transaction/interceptor/TransactionAttributeSource]
    04:07:32.912 [Test worker] DEBUG org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Skipping candidate TestExecutionListener [org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener] due to a missing dependency. Specify custom listener classes or make the default listener classes and their required dependencies available. Offending class: [org/springframework/transaction/interceptor/TransactionAttribute]
    04:07:32.912 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@bcec031, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@21005f6c, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@32f0fba8, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@545de5a4, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@29ef6856, org.springframework.test.context.support.DirtiesContextTestExecutionListener@ab7a938, org.springframework.test.context.event.EventPublishingTestExecutionListener@3faf2e7d, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@4648ce9, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@569bf9eb, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@61526469, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@274872f8, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@76ba13c, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@eb6449b]
    04:07:32.915 [Test worker] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: context [DefaultTestContext@c7a975a testClass = ImageServiceApplicationTests, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@2c1b9e4b testClass = ImageServiceApplicationTests, locations = '{}', classes = '{class org.sagebionetworks.openchallenges.image.service.ImageServiceApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@c94fd30, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@38aa816f, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@13330ac6, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@4331d187, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@7e4204e2, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@e1de817], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true]], class annotated with @DirtiesContext [false] with mode [null].

      .   ____          _            __ _ _
     /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
    ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
     \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
      '  |____| .__|_| |_|_| |_\__, | / / / /
     =========|_|==============|___/=/_/_/_/
     :: Spring Boot ::                (v2.7.8)

    2023-05-02 04:07:33.296  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.o.i.s.ImageServiceApplicationTests   : Starting ImageServiceApplicationTests using Java 17.0.6 on 0fb43fed7afd with PID 22991 (started by vscode in /workspaces/sage-monorepo/apps/openchallenges/image-service)
    2023-05-02 04:07:33.297  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.o.i.s.ImageServiceApplicationTests   : The following 1 profile is active: "test"
    2023-05-02 04:07:34.643  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.cloud.context.scope.GenericScope     : BeanFactory id=48671eb2-8304-3ca2-8359-4d0e3294064f
    2023-05-02 04:07:38.179  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] DiscoveryClientOptionalArgsConfiguration : Eureka HTTP Client uses RestTemplate.
    2023-05-02 04:07:38.349  WARN [openchallenges-image-service,,] 22991 --- [pool-1-thread-1] o.s.c.s.a.z.ZipkinAutoConfiguration      : Check result of the [RestTemplateSender{http://localhost:9411/api/v2/spans}] contains an error [CheckResult{ok=false, error=org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9411/api/v2/spans": Connection refused; nested exception is java.net.ConnectException: Connection refused}]
    2023-05-02 04:07:38.651  WARN [openchallenges-image-service,,] 22991 --- [    Test worker] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.
    2023-05-02 04:07:38.727  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
    2023-05-02 04:07:38.801  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.o.i.s.ImageServiceApplicationTests   : Started ImageServiceApplicationTests in 5.85 seconds (JVM running for 6.851)
    2023-05-02 04:07:38.843  INFO [openchallenges-image-service,,] 22991 --- [    Test worker] o.s.o.i.service.ImageServiceApplication  : Welcome to the image service.
Running test: Test contextLoads()(org.sagebionetworks.openchallenges.image.service.ImageServiceApplicationTests)
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

ImageServiceApplicationTests > contextLoads() PASSED
Running test: Test getImage_ShouldReturnImage_WhenObjectKeyIsPassed()(org.sagebionetworks.openchallenges.image.service.service.ImageServiceTest)

ImageServiceTest > getImage_ShouldReturnImage_WhenObjectKeyIsPassed() PASSED
2023-05-02 04:07:39.950  INFO [openchallenges-image-service,,] 22991 --- [       Thread-7] o.s.c.s.a.z.ZipkinAutoConfiguration      : Flushing remaining spans on shutdown

BUILD SUCCESSFUL in 11s
5 actionable tasks: 2 executed, 3 up-to-dat
```

### CODE REVIEW

**Comment by mdsage1** [comment]
Error message prior to latest update:
> Task :compileTestJava FAILED
/workspaces/sage-monorepo/apps/openchallenges/image-service/src/test/java/org/sagebionetworks/openchallenges/image/service/service/ImageServiceTest.java:42: error: no suitable method found for thenReturn(Thumbor)
    when(thumbor.buildImage(anyString())).thenReturn(thumbor);
                                         ^
    method OngoingStubbing.thenReturn(ThumborUrlBuilder) is not applicable
      (argument mismatch; Thumbor cannot be converted to ThumborUrlBuilder)
    method OngoingStubbing.thenReturn(ThumborUrlBuilder,ThumborUrlBuilder...) is not applicable
      (argument mismatch; Thumbor cannot be converted to ThumborUrlBuilder)
/workspaces/sage-monorepo/apps/openchallenges/image-service/src/test/java/org/sagebionetworks/openchallenges/image/service/service/ImageServiceTest.java:43: error: cannot find symbol
    when(thumbor.resize(isA(int.class), isA(int.class))).thenReturn(thumbor);
                ^
  symbol:   method resize(Integer,Integer)
  location: variable thumbor of type Thumbor
/workspaces/sage-monorepo/apps/openchallenges/image-service/src/test/java/org/sagebionetworks/openchallenges/image/service/service/ImageServiceTest.java:44: error: cannot find symbol
    when(thumbor.toUrl()).thenReturn(expectedImageUrl);
                ^
  symbol:   method toUrl()
  location: variable thumbor of type Thumbor
3 errors
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileTestJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
9 actionable tasks: 1 executed, 8 up-to-date
Failed to execute command: ./gradlew build 
Error: Command failed: ./gradlew build 
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runBuilderCommand (/workspaces/sage-monorepo/node_modules/@nxrocks/common/src/lib/core/jvm/utils.js:20:38)
    at runBootPluginCommand (/workspaces/sage-monorepo/node_modules/@nxrocks/nx-spring-boot/src/utils/boot-utils.js:15:43)
    at /workspaces/sage-monorepo/node_modules/@nxrocks/nx-spring-boot/src/executors/build/executor.js:10:54
    at Generator.next (<anonymous>)
    at /workspaces/sage-monorepo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspaces/sage-monorepo/node_modules/tslib/tslib.js:114:16)
    at buildExecutor (/workspaces/sage-monorepo/node_modules/@nxrocks/nx-spring-boot/src/executors/build/executor.js:8:20)
    at /workspaces/sage-monorepo/node_modules/nx/src/command-line/run.js:102:23
    at Generator.next (<anonymous>)
    at /workspaces/sage-monorepo/node_modules/nx/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/workspaces/sage-monorepo/node_modules/nx/node_modules/tslib/tslib.js:114:16)

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project openchallenges-image-service and 4 task(s) it depends on (14s)
 
    ✖    1/5 failed
    ✔    4/5 succeeded [2 read from cache]

**Comment by tschaffter** [comment]
I can reproduce locally the errors reported by GitHub:

```console
vscode@0fb43fed7afd:/workspaces/sage-monorepo/apps/openchallenges/image-service$ ./gradlew test

> Task :test

ImageServiceApplicationTests > contextLoads() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:98
        Caused by: org.springframework.cloud.config.client.ConfigClientFailFastException at ConfigServerConfigDataLoader.java:197
            Caused by: org.springframework.web.client.ResourceAccessException at RestTemplate.java:791
                Caused by: java.net.ConnectException at Net.java:-2

ImageServiceTest > givenImage_ImageDto_MatchURL() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:98
        Caused by: org.springframework.cloud.config.client.ConfigClientFailFastException at ConfigServerConfigDataLoader.java:197
            Caused by: org.springframework.web.client.ResourceAccessException at RestTemplate.java:791
                Caused by: java.net.ConnectException at Net.java:-2

2 tests completed, 2 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///workspaces/sage-monorepo/apps/openchallenges/image-service/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
4 actionable tasks: 3 executed, 1 up-to-date
```

**Comment by tschaffter** [comment]
> Creating objects within a class' constructor is bad practice (Dependency inversion principle). A common way to get such code under test is adding a new constructor that is package private.

I'm currently creating the Thumbor object in the constructor of the image service, which gives me trouble as I'm trying to mock the Thumbor object.

**Comment by tschaffter** [comment]
## Required components

Running the unit tests of the image service successfully requires the config server to be accessible, which is not the case when the tests are run by GitHub CI/CD workflow.

Running the tests will also thrown an error if the service registry is not accessible. However, the tests can still pass even if the service registry is not available.

## TODO

Identify how to either mock the config server or enable the unit test to access the config server.

**Pull request merged**
