### PR TITLE
fix(ui): DOI linkout

### PR DESCRIPTION
**Pull request by vpchung**
## Changelog

* update anchor element to actually link out instead of going back to home (due to `#`)
* link will not be displayed if there is no DOI
* add `doi` to SQL files (default value will be an empty string for now)
* add `doi` to the challenge service

## Preview

Recording 2023-06-08 at 15 29 27

### Remaining TODOs

* ~The challenge service will need to be modified to support the `doi` feature - to be added by @tschaffter~
* ~Replace `mockDoi` with `challenge.doi` - to be completed by @vpchung after #1534~

### CODE REVIEW

**Comment by vpchung** [comment]
`doi` is not yet part of the data model, so we are still using a `mockDOI` variable, which is currently set to `09.1937/09219137`.  This will link out to an error page (as shown in the screen capture).  For the private preview, should we continue with this behavior or should we instead have DOI be empty?

**Comment by tschaffter** [comment]
@vpchung What is your preference?

**Comment by vpchung** [comment]
@tschaffter I much rather leave it empty if we can't find a real DOI.  But I also know you want to showcase what we could do, so.... ¯\_(ツ)_/¯

**Comment by tschaffter** [comment]
> I much rather leave it empty if we can't find a real DOI

You are right. What we should avoid are behaviors that the users may think are bugs or use incorrect data, unless they can reasonably look like placeholder such as `12345...`.

We can either:
1. leave the field empty for now (showing the key `DOI` will be enough to let users know that these value will be available at some point) and come back to this feature later.
2. update the backend to support the DOI (update API description, update SQL files, update challenge service, update API client for angular) and close this feature.

I can modify the challenge service to support this feature. Could you update the SQL file(s)?

**Comment by vpchung** [comment]
> Could you update the SQL file(s)?

Yes, I can add that.

**Comment by vpchung** [comment]
@tschaffter updated!

Screen Shot 2023-06-08 at 10 30 03 AM

**Comment by tschaffter** [comment]
@vpchung I updated the API description and the challenge service. Do you want to give a try to updating the API client for Angular (`nx openapi-generate openchallenges-api-client-angular`) and updating the app to use the new property of the `Challenge` object?

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
