### PR TITLE
fix(openchallenges): update static plot numbers

### LINKED ISSUE #2499: [Bug] The plot of the OC home page is out of sync
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

Until recently, we updated the OC data files (CSV) manually. This also applied to the data of the plot on the OC home page that were updated manually too.

We are now using a GH workflow to update the CSV files but not the plot data. As a result, the plot data may become out of sync with the content of the DB.

### Expected behavior

The plot reflects the content of the OC DB.

### Anything else?

Task:

- [ ] Update the OC challenge service to automatically generate the plot data instead of relying on static values.

### Commit ID

_No response_

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vpchung**
Temporary fix for #2499 (but we will probably want a more permanent fix)

## Changelog
* add to script so that the static plot data is also updated with the CSV files

## Preview

> [!NOTE]
> ### [Preview of latest changes can be seen here](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2504#issuecomment-1947526943)

Screenshot 2024-02-15 at 12 57 58 PM

### CODE REVIEW

**Review by tschaffter — CHANGES_REQUESTED** [review]
There is no guarantee that `Arrays.asList` won't be used for a different use cases in this file. My suggestion:

Add a comment above the line you want to change that 1) this comment is used as a marker and should not be changed and that 2) the plot data are updated by a script and should not be modified manually.

**Comment by vpchung** [comment]
Thanks, @tschaffter . I don't know if I fully understood your suggestion, but I have added a comment to the Java file that `challengeCounts` should not be touched.  Lmk if this is what you had in mind.

**Comment by tschaffter** [comment]
My understanding is that the script looks for the first occurrence of "Arrays.asList" to detect where to make the change. If we use "Arrays.asList" above the existing one, e.g. in another function, then the script won't update the correct "Arrays.asList". A solution is to add a comment above the line you want to change to use as a marker, i.e. you would change your regular expression so that the script looks for the location of the comment and then modifies the line that follows the comment.

**Comment by vpchung** [comment]
Ah I see. The regex looks for `Arrays.asList(...);` where `...` is either a number, a whitespace, or a comma, which I thought was specific enough.

But if adding a comment marker is the safer approach, I will do so.

**Comment by vpchung** [comment]
Script has been updated to look for a specific marker for replacement (`/* AUTO-UPDATE MARKER */`):

Screenshot 2024-02-15 at 3 55 39 PM

**Review by tschaffter — APPROVED** [review]
Looks good to me! One thing to check: can you run [`nx format-check openchallenges-challenge-service`](https://github.com/Sage-Bionetworks/sage-monorepo/blob/89e285e8defce8dd1df49334cafccdeef5bd527b/apps/openchallenges/challenge-service/project.json#L56-L61) (once locally) to make sure that the formatter runs successfully?

**Comment by vpchung** [comment]
> can you run [nx format-check openchallenges-challenge-service](https://github.com/Sage-Bionetworks/sage-monorepo/blob/89e285e8defce8dd1df49334cafccdeef5bd527b/apps/openchallenges/challenge-service/project.json#L56-L61) (once locally) to make sure that the formatter runs successfully with the modified Java file?

Done! ✅ No change found.

```bash
$ nx format-check openchallenges-challenge-service

> nx run openchallenges-challenge-service:format-check

Executing command: ./gradlew spotlessCheck 
Starting a Gradle Daemon (subsequent builds will be faster)
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
> Task :spotlessInternalRegisterDependencies UP-TO-DATE
> Task :spotlessJava UP-TO-DATE
> Task :spotlessJavaCheck UP-TO-DATE
> Task :spotlessCheck UP-TO-DATE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD SUCCESSFUL in 6s
3 actionable tasks: 3 up-to-date

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target format-check for project openchallenges-challenge-service (8s)
 
   View logs and investigate cache misses at https://cloud.nx.app/runs/E7WhtSgmAO
```

**Pull request merged**
