### PR TITLE
fix(openchallenges): set specific div height for 404 page

### LINKED ISSUE #2346: [Bug] Revisit the Not Found page in OC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

The content of the 404 page is partially masked by the navbar.

image

### Expected behavior

The content is not cropped.

### Anything else?

_No response_

### Commit ID

_No response_

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #2346 

## Changelog
* set min-height as 100% the viewport's height minus the navbar height
* remove unneeded scss definition

## Preview
Screenshot 2023-11-10 at 2 48 56 PM

@tschaffter does the 404 page look better on your end with this new parameter?

### CODE REVIEW

**Comment by vpchung** [comment]
Another option is to remove the footer altogether from the 404 page (notice the lack of a scroll bar):

Screenshot 2023-11-10 at 2 53 25 PM

**Review by tschaffter — COMMENTED** [review]
I shared in the ticket that the 404 container does indeed overlap with the navbar in some cases (small viewport). Unless I'm checking that in the wrong way?

We should keep the footer on the 404 page: it includes valuable information about the app which may be particularly important for users who land on this page.

**Comment by tschaffter** [comment]
See https://github.com/Sage-Bionetworks/sage-monorepo/issues/2346#issuecomment-1806549572

**Comment by vpchung** [comment]
This proposal should already address what you had noted, e.g.

**The container starts after the navbar:**
Screenshot 2023-11-16 at 12 50 26 PM

**The `.err-code` is well below the navbar:**
Screenshot 2023-11-16 at 12 50 32 PM

**Comment by vpchung** [comment]
OK. I have added some padding so that the text is also within the main container:
Screenshot 2023-11-16 at 12 57 52 PM

**Review by tschaffter — APPROVED** [review]
Test and approved! The latest change did fix the issue.

**Pull request merged**
