### PR TITLE
feat(schematic): add generate excel manifest endpoint

### PR DESCRIPTION
**Pull request by andrewelamb**
- fixes [FDS-1605]
- adds generate excel manifest endpoint
- removes input validation from generate google sheets manifest endoint (functionality moved to schematic)
- removed defaults from generate google sheets manifest endoint (to help testing)
- files for runing the API locally added to gitignore file

[FDS-1605]: https://sagebionetworks.jira.com/browse/FDS-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by linglp — CHANGES_REQUESTED** [review]
@andrewelamb I think users need to be able to download the excel file as an attachment. When I tried the endpoint you made, by using the default parameters, I saw: 
Screen Shot 2024-03-19 at 6 30 53 PM

This is not the expected behavior because front-end apps like DCA can't read files downloaded on the schematic side. They can't read from file path: `"/workspaces/sage-monorepo/apps/schematic/api/Example.Patient.manifest.xlsx"` and get the manifest as an excel file. In summary, Schematic APIs would need to forward the excel file somehow to the front-end app when the endpoint gets called and can't just forward a path.

**Comment by tschaffter** [comment]
@andrewelamb Is this PR still relevant?

**Comment by andrewelamb** [comment]
@tschaffter Yes, I'm hoping to get back to this next week.

**Comment by tschaffter** [comment]
@andrewelamb Could you please share an update about this PR?

**Comment by andrewelamb** [comment]
I'm goign to close this PR. I'll start a new one since this branch is so behind main now.

**Pull request closed without merging**
