### PR TITLE
feat: Create a template for submitting bug reports

### LINKED ISSUE #1172: Create a template for submitting bug reports
See [GitHub - Syntax for issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

### PR DESCRIPTION
**Pull request by tschaffter**
Fixes #1172 

## Changelog

- Add a template for submitting bug reports

## TODO

- [x] Invite submit to provide screenshots (e.g. when they complement logs)

## Notes

- Another template will be added to request a new feature (different from submitting a bug).
- I wish there was a way to render the templates before merging them to the main branch.

### CODE REVIEW

**Review by vpchung — APPROVED** [review]
I would suggest the option to provide screenshots as well.

**Review by rrchai — APPROVED** [review]
LGTM!

You may already know, "you can store multiple issue templates in an ISSUE_TEMPLATE subdirectory within the root or docs/ directories", i.e `ISSUE_TEMPLATE/bug_report.yaml`

**Comment by tschaffter** [comment]
I knew but forgot. Thanks for the reminder, Rong!

**Comment by tschaffter** [comment]
## Update

- Only one text area for additional information: invite submitter to submit logs, screenshot there.
- Create the folder ISSUE_TEMPLATE

**Pull request merged**
