### PR TITLE
style(ui): fix login and register pages

### PR DESCRIPTION
**Pull request by vpchung**
Addresses #1151 :

### Login page

Screen Shot 2023-01-12 at 11 24 34 PM

### Register page

Screen Shot 2023-01-12 at 11 24 25 PM

I think some fine-tuning details are still needed, but this should be enough for our closed launch.

### CODE REVIEW

**Review by rrchai — APPROVED** [review]
LGTM

**Comment by vpchung** [comment]
Thanks for the quick review, @rrchai !

I'll probably merge this after I talk to Adam about the page designs.

**Review by tschaffter — COMMENTED** [review]
Proposed changes:

- Login page
  - Use the same width for the credential fields and the Log In button.
  - Place `Forgot password?` closer to the password field.
  - Place each SSO button on their own line to be more future proof towards longer name.
  - (Optional) Separate credentials fields + Log in button from SSO buttons
    - See example from Keycloak below.

image


- Registration page
  - Ask prospective user to enter their username first
    - Start with easier step + know if username is available (in case user want to use this information to create a custom email address like "thomas.schaffter+openchallengesbot@gmail.com").

**Comment by vpchung** [comment]
Thanks, @tschaffter !  I agree with your proposed changes, and had the same thoughts myself when I created the PR.  But given the current timeline, I'd like to hold off on implementing the finer details for now if that's okay with you and @rrchai ?

**Comment by vpchung** [comment]
Ah, for this:

> Ask prospective user to enter their username first

I was actually thinking of forgoing `username` altogether, and ask them to make it on the next page!  I read some articles on what makes a good registration UI is to include as little fields as possible (max of 4 is ideal), as more fields is more likely to deter someone from signing up.  What are your guys' thoughts?

**Comment by tschaffter** [comment]
Sounds like a good plan. Let's merge this PR and address the comments in another one. Otherwise this PR may quickly accumulate conflicts. This PR also provides us with a clean environment to continue the development of authentication next sprint. Thanks!

**Comment by vpchung** [comment]
Great!  I started a ticket for the proposed changes in #1194

**Pull request merged**
