### PR TITLE
fix(ui): Add default text for empty fields on profile pages

### LINKED ISSUE #1834: [Enhancement] Provide text for empty fields on Profile pages
## Sage Design feedback

Current profile pages:

Image

It may be a good idea to provide some explicit text, e.g. "None provided", rather than leaving fields empty.  That way, it's clear that this information was not found and that it's not a bug with the frontend.

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #1834 

## Changelog
* display "Not available" for empty DOI
* display "Not available" for empty Input Data Types
* display "Not available" for empty Incentives

## Preview
Screenshot 2023-08-02 at 12 52 05 PM

### CODE REVIEW

**Review by rrchai — APPROVED** [review]
LGTM. Thanks!

Out of curiosity, would you think the "Not available" needs to be de-emphasized to let users concentrate on other filled info. Something like below?

Screen Shot 2023-08-02 at 4 08 19 PM
Screen Shot 2023-08-02 at 4 08 38 PM
Screen Shot 2023-08-02 at 4 08 45 PM

**Comment by tschaffter** [comment]
I support the suggestion made by @rrchai , using light gray. For me using italic is a weight to emphasis a word so I wouldn't use that font.

**Review by tschaffter — APPROVED** [review]

**Comment by vpchung** [comment]
@rrchai I was thinking the same!  But didn't want to put in the effort (yet) 😅 

But since everyone has the same idea, I will add the grey text.

**Comment by vpchung** [comment]
**Challenge profile**

Screenshot 2023-08-02 at 3 01 52 PM

**Organization profile**

Screenshot 2023-08-02 at 3 01 44 PM

**Comment by vpchung** [comment]
@tschaffter @rrchai I know you both approved already, but I attached some screenshots of the grey text.

Will merge shortly!

**Comment by tschaffter** [comment]
Perfect!

**Pull request merged**
