### PR TITLE
feat: add notebook from Google Colab

### LINKED ISSUE #1222: Add Verena's Kaggle exploration notebook to the monorepo
See #1221 for background information.

### PR DESCRIPTION
**Pull request by vpchung**
Closes #1222 .

Screen Shot 2023-02-17 at 9 59 12 AM

### CODE REVIEW

**Comment by tschaffter** [comment]
@vpchung I have an error when running the notebook:

```python
!mkdir -p ~/.kaggle

import codecs
uploaded_file = uploader.value[0]
with open("/home/vscode/.kaggle/kaggle.json", "w") as cred:
    cred.write(codecs.decode(uploaded_file.content, encoding="utf-8") + "\n")
    
!chmod 600 ~/.kaggle/kaggle.json
```

Error:

```console
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], line 4
      1 get_ipython().system('mkdir -p ~/.kaggle')
      3 import codecs
----> 4 uploaded_file = uploader.value[0]
      5 with open("/home/vscode/.kaggle/kaggle.json", "w") as cred:
      6     cred.write(codecs.decode(uploaded_file.content, encoding="utf-8") + "\n")

IndexError: tuple index out of range
```

**Review by tschaffter — CHANGES_REQUESTED** [review]
See comment in the thread about auth to Kaggle.

**Comment by vpchung** [comment]
@tschaffter from [their docs](https://www.kaggle.com/docs/api#authentication), the Kaggle CLI tool specifically looks for a file called `kaggle.json`.

Did you run the notebook in the web browser or from the IDE?  From what I've gathered, the FileUpload widget only works in browser so perhaps that explains your error?

**Comment by vpchung** [comment]
@tschaffter to be honest, I don't think my notebook will add much value to the repo, so maybe this is not worth debugging.

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
