### PR TITLE
fix(openchallenges): fix challenge descriptions

### PR DESCRIPTION
**Pull request by vpchung**
## Changelog

* fix acronym casing in challenge descriptions, e.g. miccai/Miccai → MICCAI, covid-19 → COVID-19, etc.
* convert descriptions in proper case to sentence case
* typo fixes

### CODE REVIEW

**Comment by vpchung** [comment]
Ah, looks like some of the descriptions are proper casing.

Will need to fix that too~

**Review by gaiaandreoletti — COMMENTED** [review]
thank you @vpchung !

**Review by gaiaandreoletti — COMMENTED** [review]
great

**Review by tschaffter — APPROVED** [review]
Approving on behalf of Gaia (Slack)

**Comment by tschaffter** [comment]
We should move away from cropped headlines, and prefer empty headlines until we get one that meet the specification.

**Comment by tschaffter** [comment]
See last commit and comment. Merging now.

**Pull request merged**
