### PR TITLE
fix(ui): UI cleanup

### PR DESCRIPTION
**Pull request by vpchung**
Using #1350 as a guide, this PR includes an initial cleanup to some of the more jarring issues of the app, for example: the skewed images on the Meet the Team page.

preview

> **Note** During this exercise, I noticed we also need to do a cleanup with the SCSS sheets as well (saving that for another PR).

### CODE REVIEW

**Review by tschaffter — APPROVED** [review]
Here are some observation:

- The challenge and organization cards have a dynamic height depending on their content. I initially thought that it would be better to have the same height so that it's easier to compare a given piece of information (e.g. challenge status) across cards when they are at the same vertical location. For now the look and feel feels OK to me, though I'm interested in the thoughts of others.
- I noticed that some challenges have an invalid slug but this is probably not related to this PR.
  - I reported this issue as a bug.
- I could not access the challenge and organization pages. I think that this is expected at this point as we are still working on the routes.

**Comment by rrchai** [comment]
@vpchung  Thanks for improving the app UI.

The icon and label seems not aligned in the filters - not sure if it's just on my end

Screen Shot 2023-03-31 at 8 04 52 PM

**Review by rrchai — APPROVED** [review]
LGTM overall! Thanks.

**Comment by tschaffter** [comment]
I confirm that the label of checkboxes and radio buttons are not aligned.

image

**Review by tschaffter — CHANGES_REQUESTED** [review]
See comments above about misaligned labels.

EDIT: I checked and there is no misalignment on `main`.

**Comment by vpchung** [comment]
Thanks, @rrchai! I noticed the same for the breadcrumbs so I made a note of it in #1350.  I'll add the facet misalignments too.

**Comment by vpchung** [comment]
> [tschaffter](https://github.com/tschaffter) requested changes [3 days ago](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1433#pullrequestreview-1367789717)

Oh, nevermind, I'll address them in this PR then.

**Comment by vpchung** [comment]
Something weird happened on my end, so I am starting over. Closing this PR for now.

**Pull request closed without merging**
