### PR TITLE
feat(openchallenges): update Sage logo

### PR DESCRIPTION
**Pull request by vpchung**
> [!IMPORTANT]
> To be merged _after_ March 4th!

## Changelog

* use Sage's new logo 
* remove `height` specifications; since the new logos are smaller than the previous logos, specifying the heights made the logos looked blurry, so they have been removed

## Preview

* **Footer**
Screenshot 2024-03-01 at 1 29 38 PM

* **Meet the Team page**
Screenshot 2024-02-14 at 5 02 35 PM

* **Sage profile**
Screenshot 2024-03-01 at 1 26 35 PM

### CODE REVIEW

**Comment by vpchung** [comment]
@rrchai @tschaffter seeing that Monday is the release of Sage's new look, this PR is now ready for review 🎉

**Review by tschaffter — CHANGES_REQUESTED** [review]
The new official Sage logo is getting margin. We should use this new version when available.

**Comment by vpchung** [comment]
> The new official Sage logo is getting margin. We should use this new version when available.

This is addressed in #2540

**Review by tschaffter — APPROVED** [review]
LGTM

**Pull request merged**
