### PR TITLE
feat: Sort challenges by Closing soon, starting soon (backend)

### LINKED ISSUE #1157: Sort challenges by Closing soon, starting soon (backend)
Closing soon: current date < end date AND sort by end date in desc
Starting soon: current date < start date AND sort by start date in desc

### PR DESCRIPTION
**Pull request by tschaffter**
Fixes #1157 

## Changelog

- Add two example challenges: one organized in 2024 and one in 2025.
- Add the option to sort challenges by `starting_soon` and `ending_soon`.
- Accept `null` direction so that the backend can decide on the default to choose (`desc` or `asc`).
  - Example 1: `/challenges?sort=starred` should use the default direction `desc`
  - Example 2: `/challenges?sort=starting_soon` should use the default direction `asc` to show first the challenges that start the closest to now.

## Notes

- Changing the OA description to accept `null` direction has one minor negative side effect: The OA generator for Java will handles the creation of enums as follows: "if the specified value does not exist, return `null`". It would have been preferable to check if the value specified is in (`asc`, `desc`, `null`), and otherwise throw a Bad Request exception for other values. This behavior can be implemented by modifying the OA generator template for enums. However, I won't implement that in this PR as not strictly required.

## Preview

Sort the challenges by how soon they start.

> **Note**
> The challenges with a start date before "now" or with a `null` value are not included.

```console
GET {{basePath}}/challenges?sort=starting_soon

HTTP/1.1 200 
{
  "number": 0,
  "size": 100,
  "totalElements": 2,
  "totalPages": 1,
  "hasNext": false,
  "hasPrevious": false,
  "challenges": [
    {
      "id": 4,
      "name": "Awesome Challenge 2024",
      "headline": "Example headline",
      "description": "Example description",
      "status": "completed",
      "difficulty": "advanced",
      "platform": {
        "id": 2,
        "slug": "codalab",
        "name": "CodaLab"
      },
      "incentives": [],
      "submissionTypes": [],
      "inputDataTypes": [],
      "startDate": "2024-01-01",
      "endDate": "2024-02-01",
      "starredCount": 0,
      "createdAt": "2023-01-17T23:34:52Z",
      "updatedAt": "2023-01-17T23:34:52Z"
    },
    {
      "id": 5,
      "name": "Awesome Challenge 2025",
      "headline": "Example headline",
      "description": "Example description",
      "status": "completed",
      "difficulty": "advanced",
      "platform": {
        "id": 2,
        "slug": "codalab",
        "name": "CodaLab"
      },
      "incentives": [],
      "submissionTypes": [],
      "inputDataTypes": [],
      "startDate": "2025-01-01",
      "endDate": "2025-02-01",
      "starredCount": 0,
      "createdAt": "2023-01-17T23:34:52Z",
      "updatedAt": "2023-01-17T23:34:52Z"
    }
  ]
}
```

Sort the challenges by how soon they end:

> **Note**
> The challenges with an end date before "now" or with a `null` value are not included.

```console
GET {{basePath}}/challenges?sort=ending_soon

HTTP/1.1 200 
{
  "number": 0,
  "size": 100,
  "totalElements": 2,
  "totalPages": 1,
  "hasNext": false,
  "hasPrevious": false,
  "challenges": [
    {
      "id": 4,
      "name": "Awesome Challenge 2024",
      "headline": "Example headline",
      "description": "Example description",
      "status": "completed",
      "difficulty": "advanced",
      "platform": {
        "id": 2,
        "slug": "codalab",
        "name": "CodaLab"
      },
      "incentives": [],
      "submissionTypes": [],
      "inputDataTypes": [],
      "startDate": "2024-01-01",,
      "endDate": "2024-02-01",
      "starredCount": 0,
      "createdAt": "2023-01-17T23:37:20Z",
      "updatedAt": "2023-01-17T23:37:20Z"
    },
    {
      "id": 5,
      "name": "Awesome Challenge 2025",
      "headline": "Example headline",
      "description": "Example description",
      "status": "completed",
      "difficulty": "advanced",
      "platform": {
        "id": 2,
        "slug": "codalab",
        "name": "CodaLab"
      },
      "incentives": [],
      "submissionTypes": [],
      "inputDataTypes": [],
      "startDate": "2025-01-01",
      "endDate": "2025-02-01",
      "starredCount": 0,
      "createdAt": "2023-01-17T23:37:20Z",
      "updatedAt": "2023-01-17T23:37:20Z"
    }
  ]
}
```

### CODE REVIEW

**Comment by rrchai** [comment]
@tschaffter Based on the sorted results, it seems the challenges are not filtered by status prior to sorting by "closing soon" or "starting soon"?

**Comment by tschaffter** [comment]
@rrchai My assumption is that the start and end date are the ground truth for defining the status of a challenge. Hence, the property `status` is a proxy of the start and end date. In that case, it's preferable to use the ground truth (start and end date) to filter results.

See also this [comment](https://github.com/Sage-Bionetworks/sage-monorepo/issues/1207#issuecomment-1386277453).

**Comment by rrchai** [comment]
@tschaffter Thanks for the link. I missed that ticket.

It seems the current "starting_soon" and "ending_soon" will sort the challenges with `startDate`/`endDate` later than today respectively. Thus, the "starting_soon" will include the challenges with "upcoming", while "ending_soon" will include the challenges with "active" and "upcoming".

^ works for me, although I feel "starting_soon" and "ending_soon" should be more strict to match the descriptions:
- "starting_soon" -> only "upcoming" challenges
- "ending_soon" -> only "active" challenges

@tschaffter I have a question that what if both status filter and "starting_soon"/"ending_soon" sort applied, e.g. `GET {{basePath}}/challenges?id=active&sort=starting_soon`, will filter be applied prior to sort?

**Comment by tschaffter** [comment]
@rrchai Let's jump in a brief call tomorrow (Thursday) to "sort" out this PR.

**Comment by tschaffter** [comment]
I went for an implementation that assumes that the user knows what they are doing: no error are thrown if two or more filters/sort clash, the page returned will just be empty.

**Review by rrchai — APPROVED** [review]
According to the discussion, the logic behind sorting `ending_soon` and `starting_soon` makes sense to me now, especially we would like to avoid the conflicts against the status filter.

**Pull request merged**
