### PR TITLE
feat(angular): Enable to search org by searchTerm in the dropdown widget

### LINKED ISSUE #1421: [Story] Enable to search org by searchTerm in the dropdown widget
### What projects is this story for?

OpenChallenges

### Description

The current search field and dropdown on the widget come together using the existing component from primeng ([MultiSelect](https://primeng.org/multiselect)). The search field will only filter the label of options. We would like to utilize the search field to filter the organizations by `searchTerm`.

As @tschaffter purposed, the widget should behave like below:
- The user starts typing in the widget search field. 400 ms after the user stopped typing, a request is sent to the org service to find orgs that match the search terms.
- The widget receives a list of orgs based on the search terms. The list of orgs in the widget is updated.

### Acceptance criteria

- the org can be filtered by the search term in the dropdown

### Tasks

- #1423 

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### PR DESCRIPTION
**Pull request by rrchai**
- fixes #1421

TODO:
- [x] since the dropdown component is changed for the org filter in this pr, the input data type filter is also required to be changed using `searchTerms`. Update the frontend codes of input data type filter in preparation of the backend update (#1451)

Future work:
- [ ] implement lazyLoading in the dropdown - the data fetched from database will be based on the scrollbar's changes. (refer to the attempt in [15a619c](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1423/commits/15a619c56664234764c43811a6357b3ba02438f2))

### CODE REVIEW

**Comment by tschaffter** [comment]
This looks like a great start! Thanks @rrchai !

**Comment by rrchai** [comment]
When the search term in search field is updated, I can get the orgs from the backend immediately. However, there's still delays/inconsistence in the options of dropdown - need to more time to debug,

**Comment by tschaffter** [comment]
@rrchai What is your target date to complete this PR?

**Comment by rrchai** [comment]
@tschaffter let's target by next Tuesday.

**Comment by rrchai** [comment]
> When the search term in search field is updated, I can get the orgs from the backend immediately. However, there's still delays/inconsistence in the options of dropdown. One thought is there is conflict against the default filter function of the component. If so,I need to remove the default search bar and add a custom the search bar in the component - need more time to debug.

I can confirm after replace by custom search bar, the options show the expected results with no obvious delays. 

- [ ] The custom search bar needs to be updated with styles to match with the styles of dropdown.

**Comment by rrchai** [comment]
TODO: 
- [ ] enable input data type dropdown to use `searchTerms` to find the item.

**Review by tschaffter — COMMENTED** [review]
The expected behavior should be described at the top of this discussion thread, along with ideas of future work.

On my end the organization filter seems to work. The initial list of organizations seems unordered, but I would expect it to be ordered alphabetically thanks to a recent PR.

EDIT:

- I cannot select more than one organization.
- Sometimes the value "empty" appears in the filter:
- 
image

**Comment by rrchai** [comment]
> The initial list of organizations seems unordered, but I would expect it to be ordered alphabetically thanks to a recent PR.

Ah, my bad. I initially thought the returned results of listOrganizations will be auto sorted by name.

**Comment by rrchai** [comment]
> I cannot select more than one organization.

I am not able to reproduce the behavior on my end - I can select multiple orgs: 
Recording 2023-04-04 at 13 05 39

>Sometimes the value "empty" appears in the filter

The bug looks familiar before I updated to use custom filter, but I am not able to reproduce now. We could dig into it later today.

**Comment by rrchai** [comment]
> I cannot select more than one organization.
Sometimes the value "empty" appears in the filter:

As discussion with @tschaffter, the bug above can be reproduced by following steps:
- search and select "DREAM"
- then search and select "IBM"
 
Based on the testing, the selection UI will only show the selections that is displayed in the dropdown options. The "DREAM" will be removed from UI after query orgs by ‘IBM’ (since it only shows IBM in the dropdown now).

---
Now the bug is fixed by concatenating the selections to the searched results, so the selections will be always in the dropdown list:
Recording 2023-04-05 at 13 10 18

**Review by tschaffter — APPROVED** [review]
LGTM

**Review by vpchung — APPROVED** [review]

**Comment by rrchai** [comment]
@tschaffter 

the search query `http://localhost:8085/v1/challengeInputDataTypes?searchTerms=genmoic` returns the full list of input data types. Is the searchTerms filtering inputDataTypes as expected on your end?

**Comment by tschaffter** [comment]
Is the search term "genmoic" what you actually wanted to try? I would expect the search to return an empty list, but that doesn't seem to be what you get.

**Comment by rrchai** [comment]
The "bug" is described in #1463.

The frontend codes for input data type filter has been updated in this pr. I am merging this pr to #1403.

**Pull request merged**
