### PR TITLE
chore(openchallenges): add all public Grand Challenges

### PR DESCRIPTION
**Pull request by tschaffter**
## Changelog

- [x] #2351 
- [x] #2357
- [x] #2360

### CODE REVIEW

**Comment by tschaffter** [comment]
@vpchung I opened this PR so I can't technically review it. I did test the PR locally and it looks good to me. Couple of notes:

- Most GC challenges don't have start and/or end date as discussed on Slack
- The challenge logo comes from GC website. This comes with some limitations:
  - The image may much larger than needed and take time to load. Meanwhile, the logo will appear white with the alternative text (see screenshot)
  - The image may not be square. The OC style displays the image with an 1:1 aspect ratio, in which case the image would appear distorted.

image

**Comment by vpchung** [comment]
Thanks, @tschaffter . I know this isn't what you intended to catch, but your screenshot for the CAMEO challenge (not GC as stated) was a bug in the curation.  This will be fixed with #2360 .

Re: the other image links, should we ignore the image links from GC until a solution for outside avatar links is handled?

**Comment by tschaffter** [comment]
> Re: the other image links, should we ignore the image links from GC until a solution for outside avatar links is handled?

Let's keep the images to bring more colors to OC.

The "loading glitch" is a minor issue that we can fix in one of the next releases. Based on a random sampling of the GC challenges, most of the logos have a 1:1 aspect ratio and look fine on the challenge profile page.

**Comment by vpchung** [comment]
> Let's keep the images to bring more colors to OC.

You know, I never actually checked whether the logos were displayed.  This is awesome!!

Screenshot 2023-11-16 at 3 11 22 PM

**Comment by tschaffter** [comment]
@vpchung Checkout this one: http://localhost:8000/challenge/376

**Review by vpchung — APPROVED** [review]

**Pull request merged**
