### PR TITLE
fix(ui): UI cleanup, part II

### LINKED ISSUE #1474: [Story] Improve the challenge and organization profile pages
### What projects is this story for?

OpenChallenges

### As a user, I want

To improve the look and feel of the overall app, including the profile pages

## Must have

- [x] Add more images to the homepage
- [x] Remove user-related functionality from the navbar
    - [x] Log In
    - [x] User dropdown
- [x] Add padding around the challenge profile page
- [x] Re-align the text in the challenge profile page's breadcrumbs
- [x] Remove "Topics" section from the challenge profile page
- [x] Merge "Challenge Details" tab into the "Overview" page
- [x] Remove "Edit Profile" text from organization profile page
    - [x] In the mockup, we currently use "Request to Join" for non-members, but since we are not implementing a user system yet, I will use "Go to Website" instead (it will be redundant with the link in the profile) 

## Should have

- [x] Remove timeline bar from the challenge profile page (too many use cases to account for, i.e. not all challenges have defined start/end dates, etc.; does not add enough value to justify amount of effort to debug current issues)
    - [x] Add start and end dates to the top section of the challenge profile page

## Could have

- [ ] Remove the paginator for 0 results (either that or "sticky" it to the bottom)
- [x] Replace all current image assets with images from Thumbor
- [x] Increase the search bar on the home page 
    - [x] Maybe move into a new section altogether? See [mockup](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/OpenChallenges?node-id=1485-3789&t=RkWEP3YrdXIkX1pJ-0) for reference.

## Won't have (this time)

- [ ] In the Goals section, maybe do a table instead of cards?

### Acceptance criteria

- All Must-Haves should be implemented

### Tasks

_No response_

### Anything else?

_No response_

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### LINKED ISSUE #1475: Hide the login/logout/user menu from the navigation bar

### PR DESCRIPTION
**Pull request by vpchung**
Closes #1475 and closes #1474. Using #1474 as a guide, this PR features UI cleanup for the "Must have" and "Should have", as well as general finishing touches on other pages.

> **Note** although most image assets have been replaced with the objects from the image-service, a few still remain (for example, the logo in the navbar). I can replace the remaining assets once the image service allow for different dimensions being returned.

ui

### CODE REVIEW

**Comment by tschaffter** [comment]
## Suggestions

### General

- Footer
  - Don't print "POWERED BY SAGE BIONETWORKS" with all caps

### Home page

- First section
  - Reduce the empty vertical space between navbar and the first content
- Search bar
  - Can we increase the font in the search bar so that the content typed is more visible?
- Section: Are you a challenge organizer?
  - Reduce empty vertical space above and below the content
  - The image look low res
  - Note: The above two issues seems to come to the 300x300 limitation of the image service.
  - Disable the button and add a note that says that this feature is not yet available? Or redirect to instruction on how organizers can contribute to data?
- OpenChallenges was made possible by...
  - Update the list of logos
    - ITCR
    - AWS
    - Sage Bionetworks
    - See thread on slack in `#openchallenges`
  
### Challenge search page

- Remove navigation header: the user can already click on the first button in navbar for the same result
- Replace the title "Search OpenChallenges" by "Challenges"
- Reduce the empty vertical space around the title
- Show Stockard default header
  - We could use the HTML [picture](https://www.w3schools.com/tags/tag_picture.asp) tag to display it as a backup image - in case the challenge does not have a banner.

### Organization search page

- Remove navigation header: the user can already click on the first button in navbar for the same result
- Replace "Search Organization Profiles" by "Organizations"
- Reduce the empty vertical space around the title
- Org card
  - Reduce the height of the vertical space that appears on most card between the title and the card footer

### Challenge profile page

- TBD

### Organization profile page

- TBD

**Comment by tschaffter** [comment]
## Some images should actually be part of the code base

@vpchung There are a few images that should be kept on GitHub instead/in addition of moving them to S3. A rule of thumb would be that images that meet the following criteria should be part of the code base:

- The image could be considered as being part of a component, e.g. logos/icons displayed in button, the favicon image of the app, the default banner of the challenge card AND
- The image is SVG or very light (< 10 kb), e.g. favicon

Images that are part of the codebase will be packaged in the app bundle. This will enable the app to load the images instantaneously. Note that we aim to minimize the app bundle size so that the first page of the app displays faster.

For example, let's add Stockard challenge banner to the codebase (and use it from there) if it is an SVG. If the banner does not meet the rule of thumb mentioned above, then we could use a uniform background as the default/backup background.

**Comment by vpchung** [comment]
@tschaffter that makes sense.  It'll help unblock me in a couple of places.

**Comment by vpchung** [comment]
@tschaffter @mdsage1 here's the next iteration of the UI cleanup!  Which includes some changes as requested in the [feedback](https://github.com/Sage-Bionetworks/sage-monorepo/pull/1498#issuecomment-1535440245), as well as some other finishing touches:

ui-cleanup-v2

## Remaining TODO

Depending on the challenge name, some avatars are very stretched, e.g.

Screen Shot 2023-05-09 at 3 23 37 AM

I tried fixing this from the frontend side but wasn't able to.  For now, I will save this for another PR.

**Review by tschaffter — APPROVED** [review]
The pages look fantastic! 🤩

I have a minor suggestions of improvement but I prefer to keep them as separate work so that we can merge this PR sooner.

**Comment by vpchung** [comment]
@tschaffter sounds good, thanks!

Merging this one now.

**Pull request merged**
