### PR TITLE
feat(UI): Set 3 challenge cards per row for MBP 13'' viewpoint.

### LINKED ISSUE #1777: [Feature] Display 3 or more challenge results per row on MBP 13 inches (Take 2)
### What projects is this feature for?

OpenChallenges

### Description

Same request as #1527 on a MBP 13 inches.

image

With default zoom.

### Anything else?

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rrchai**
- closes #1777 

## Changelog:
- Reduce the width of filter facet to make enough space allowing 3 challenge cards per row at 1440px.
- Adjust the direction of opening dropdown filter's option box to fit in a narrow space (see preview). It's a temporary UI adjustment and this [ticket](#1832 ) will address to further improve UI of dropdown filter.
- Evenly align the challenge cards in the container
- Set fixed height on the title of challenge card, so that the texts of platforms and descriptions in card will be aligned among cards

### Before (1440px width)

Recording 2023-08-01 at 10 50 53

### After (1440px width)
Recording 2023-08-01 at 10 51 46

>**Note**
>This pr is only focusing to set 3 cards for MBP 13'' and the smaller laptop was _not_ taken into account in this pr.

### CODE REVIEW

**Review by vpchung — APPROVED** [review]
Looks so good! ⭐

**Comment by tschaffter** [comment]
I'm giving it a try on my MBP now

**Review by tschaffter — APPROVED** [review]
Tested on my MBP 13. Thanks!

**Comment by tschaffter** [comment]
@rrchai You should have used your fork to create this PR.

**Comment by rrchai** [comment]
Whoops, somehow I cloned the upstream in the devcontainer XD. Would you like me to recreate the branch from my fork?

**Comment by tschaffter** [comment]
> Would you like me to recreate the branch from my fork?

No, you can go ahead and merge it.

**Pull request merged**
