### PR TITLE
feat(openchallenges): show role of organizations in Contributors section

### LINKED ISSUE #2222: [Feature] Show the role of orgs that contribute to a challenge ⭐
### What product(s) is this feature for?

OpenChallenges

### Description

On a challenge page, we show all the orgs that contributes to it without showing their role(s). The goal of this ticket is to show this information to the users. The information is already made available to the web app by the backend.

Tasks:

- [ ] Design
- [ ] Frontend implementation

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vpchung**
~~Part 1 for #2222 , focusing on the UI~~

Fixes #2222

## Changelog
* Add 3 categories to the "Contributors" section of a challenge

## Preview
Screenshot 2023-10-27 at 2 28 27 PM

### CODE REVIEW

**Comment by tschaffter** [comment]
Thanks for implementing this feature! I'm going to make a 3-min video soon that introduces OC and I thought how cool it would be to have it implemented by then.

Here I come again about grouping elements together. 😛

The space between the subtitle and the content should be smaller than the space between the content and the next subtitle.

image

**Review by tschaffter — CHANGES_REQUESTED** [review]
See comment above

**Comment by tschaffter** [comment]
Converting to Draft as @vpchung and I are contributing to this PR.

**Comment by tschaffter** [comment]
Here is an example of challenge that includes all three types of contributions: http://localhost:4200/challenge/8?tab=contributors

> **Note**
> The link does not lead directly to the contributions tab (bug).

**Comment by tschaffter** [comment]
## Component Logic Preview

> **Note**
> Organizations are ordered by the number of challenges they have contributed to.

Recording 2023-11-01 at 20 36 32

@vpchung The component logic is ready.

**Comment by vpchung** [comment]
UI update:
Screenshot 2023-11-02 at 12 13 45 PM

**Review by rrchai — APPROVED** [review]
LGTM!

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
