### PR TITLE
feat(docker): Dockerize app

### LINKED ISSUE #1272: [Story] Dockerize the project `openchallenges-app`
### What projects is this story for?

OpenChallenges

### As a user, I want

As the person responsible for deploying the OpenChallenges, I want the OC web app to be dockerize so that I can deploy the entire OC stack with Docker Compose.

### Description

The goal of this story is to dockerize the OC web app so that it can be deployed along the rest of the stack with Docker compose.

### Acceptance criteria

- The app can be dockerized with the command `nx build-image openchallenges-app`.
- The app can be served in detach mode using docker with `nx serve-detach openchallenges-app`.
  - A docker-compose.yml is used to start the app in detached mode (see other project in this monorepo for examples).
- The Angular app is run in "production" mode (see `project.json` for references to the keyword "prod" or "production").
- Configuration values can be passed to the app as environment variables given to the container.

### Tasks

See above

- [x] #1303

### Anything else?

- The project `openchallenges-app` includes a Dockerfile that need to be modified. The current approach is to clone then entire monorepo, however it would be more convenient to build using the local files.
- If needed, configure Angular to saved the build artifacts inside the project folder instead of "${WORKSPACE_DIR}/dist/...".
- Special care need to be given to how configuration work. See the existing Dockerfile for more insights on this.

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### Timeline

To complete by the EOD of Feb 17 (one week of efforts)

### PR DESCRIPTION
**Pull request by rrchai**
- resolve #1272 

---
#### Clean the old image/container for openchallenges-app
```console
docker stop openchallenges-app
docker rm openchallenges-app
docker rmi -f sagebionetworks/openchallenges-app
```

#### Update `.env` for openchallenges-app (only need to run once)
```console
rm apps/openchallenges/app/.env
nx prepare openchallenges-app
```

#### Build the image
```console
nx build-image openchallenges-app 
workspace-build-images //  <- run if you haven't built all images before, otherwise skip
```

#### Run the full-stack containers
```console
nx serve-detach openchallenges-app
```

#### Access the app at http://localhost:4200

--- 
## For development:
```console
docker stop openchallenges-app
nx serve openchallenges-app
```

### CODE REVIEW

**Comment by tschaffter** [comment]
> nx prepare openchallenges-app // only need to run once

@rrchai The `prepare` task does not replace `.env` if it already exists. Here we should remove `.env` first before running `prepare`.

**Comment by rrchai** [comment]
>@rrchai The prepare task does not replace .env if it already exists. Here we should remove .env first before running prepare.

@tschaffter Thanks for reminding. The step is updated.

**Review by tschaffter — APPROVED** [review]

**Comment by tschaffter** [comment]
The dockerized app works great and I was able to search challenges and organizations (once merged with `main` where org full-text search lives).

**Review by vpchung — APPROVED** [review]
Works on my end too -- thanks for the clear instructions! 🎉

**Pull request merged**
