### PR TITLE
feat(openchallenges): update team page

### LINKED ISSUE #2197: [Feature] Add Gaia to the OC Team page
### What product(s) is this feature for?

OpenChallenges

### Description

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #2197 

## Changelog

* Add Gaia to the team page (@gaiaandreoletti has already approved the displayed role)
* Add a kudos shoutout to our Design and Governance team
* Add Sage Bionetworks logo (as suggested by Luca)

> [!NOTE]
> Given the recent change to the CI workflow (and increased cost), the commits for adding the kudos and Sage logo has not yet been pushed.  Once a design is approved, I will push the missing commits, then merge.

#### Option 1
Sage logo at the top, under the team description.
Screenshot 2023-10-18 at 5 48 07 PM

#### Option 2
Remove team description, Sage logo at the bottom (under the kudos)
Screenshot 2023-10-18 at 5 47 18 PM

### CODE REVIEW

**Review by tschaffter — COMMENTED** [review]
- Order the members as follow (roughly by start date; we can revise this order in 6 mo)
  - Thomas, Verena, Rong, Maria, Gaia, Jake
- What is the motivation for removing the team description?
- We may end up adding Sage logo to the navbar, in which case adding Sage logo below the team members would be preferable to put some distance between the two logos.

**Comment by vpchung** [comment]
> What is the motivation for removing the team description?

It's a fun description, but I don't know if it adds enough... value?  I think if we were to display the Sage logo, we should ideally mention that instead.

**Comment by tschaffter** [comment]
The pics on the team pages looks pixelated. An additional task for this PR is to replace them with high-res versions. Could this be the result of Thumbor's processing?

**Comment by vpchung** [comment]
Latest iteration:

Screenshot 2023-10-26 at 1 13 29 AM

**Comment by rrchai** [comment]
Look good to me overall, but I suggest to use same font size and font weight for both "Meet... " and "We're smart...". 


Screen Shot 2023-10-26 at 10 08 37 AM

**Comment by vpchung** [comment]
> use same font size and font weight for both "Meet... " and "We're smart...".

Oh, I didn't like how it looked when they were the same size, which is why I changed it.  But can switch back if that is the majority opinion.

**Comment by vpchung** [comment]
Latest iteration:

Screenshot 2023-10-27 at 2 10 37 PM

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
