### PR TITLE
feat: Filter Organization by categories (featured) (backend)

### LINKED ISSUE #1766: Set organization categories path used to filter orgs (backend)
AC:

Add `categories` property in the organization object and `featured` is one of the options.

### LINKED ISSUE #1767: Select and feature some orgs in the database (data)

### LINKED ISSUE #1774: Filter organizations by Categories (backend)
Enable to filter organizations by their categories as part of `OrganizationSearchQuery`.

### PR DESCRIPTION
**Pull request by rrchai**
- closes #1766 
- closes #1774 
- closes #1767

## Changelog

- Update the API description
  - [x] Set `OrganizationCategory` in the schemas of `organization-service`
  - [x] Enable to filter organization by "Categories"
 - Feature some orgs in database for testing
    - DREAM, MICCAI, pFDA

## Preview

List organizations that are categorized as featured

```console
GET {{basePath}}/organizations?categories=featured

HTTP/1.1 200 

{
  "number": 0,
  "size": 100,
  "totalElements": 3,
  "totalPages": 1,
  "hasNext": false,
  "hasPrevious": false,
  "organizations": [
    {
      "id": 1,
      "name": "DREAM",
      "email": "dream@sagebionetworks.org",
      "login": "dream",
      "description": "Together, we share a vision to enable individuals and groups to collaborate openly so that the “wisdom of the crowd” provides the greatest impact on science and human health.",
      "avatarKey": "logo/dream.png",
      "websiteUrl": "https://dreamchallenges.org/",
      "challengeCount": 47,
      "createdAt": "2023-07-14T21:23:05Z",
      "updatedAt": "2023-07-14T21:23:05Z",
      "acronym": "DREAM"
    },
    {
      "id": 13,
      "name": "precisionFDA",
      "email": "",
      "login": "pfda",
      "description": "A secure, collaborative, high-performance computing platform that builds a community of experts around the analysis of biological datasets in order to advance precision medicine.",
      "avatarKey": "logo/precisionfda.png",
      "websiteUrl": "https://precision.fda.gov/challenges",
      "challengeCount": 16,
      "createdAt": "2023-07-14T21:23:05Z",
      "updatedAt": "2023-07-14T21:23:05Z",
      "acronym": "pFDA"
    },
    {
      "id": 12,
      "name": "MICCAI",
      "email": "",
      "login": "miccai",
      "description": "The Medical Image Computing and Computer Assisted Intervention Society (the MICCAI Society) is dedicated to the promotion, preservation and facilitation of research, education and practice in the field of medical image computing and computer assisted medical interventions including biomedical imaging and medical robotics. The Society achieves this aim through the organization and operation of annual high quality international conferences, workshops, tutorials and publications that promote and foster the exchange and dissemination of advanced knowledge, expertise and experience in the field produced by leading institutions and outstanding scientists, physicians and educators around the world. The MICCAI Society is committed to maintaining high academic standards and independence from any personal, political or commercial interests.",
      "avatarKey": "logo/miccai.png",
      "websiteUrl": "http://www.miccai.org/special-interest-groups/challenges/miccai-registered-challenges/",
      "challengeCount": 5,
      "createdAt": "2023-07-14T21:23:05Z",
      "updatedAt": "2023-07-14T21:23:05Z",
      "acronym": "MICCAI"
    }
  ]
}

```

### CODE REVIEW

**Comment by tschaffter** [comment]
@rrchai What do you think about implementing `featured` as a filter - added to `OrganizationSearchQuery` - rather than a sorter?

**Comment by rrchai** [comment]
> What do you think about implementing featured as a filter - added to OrganizationSearchQuery - rather than a sorter?

@tschaffter That's actually a good idea, which will make easier to get featured orgs in home page. 

If 'featured" is a filter rather than a sorter, my question is where the "featured" filter should stay in org search page. Here are my thoughts:
1. Put in the left panel like other checkbox filter,s but need to be an option of another big categories to make UI consistence. Kaggle uses "Categories" for filter name and "featured" is one of the options: https://www.kaggle.com/competitions?hostSegmentIdFilter=5.
2. I can still make "featured" as sorter, even if it's part of `OrganizationSearchQuery` - just need to use different logics from other sorters.
3. Add a new icon button for "featured" in somewhere of org search page: If users click the icon, only the "featured" orgs will be listed.

What do you think @tschaffter @vpchung? Any better ideas are welcome~

**Comment by tschaffter** [comment]
@rrchai For challenges, Option 1 seems right on spot to me and has the benefit of being future-proof in the sense that I can see use adding other categories to quickly access a subset of challenges that we want to highlight. 

For organizations, which this ticket is about, the same approach should work too. I'm not sure what other categories may be for organizations in the future, maybe orgs that pledge to Open Science or orgs who are recruiting.

**Comment by vpchung** [comment]
> maybe orgs that pledge to Open Science or orgs who are recruiting.

I like this a lot!  I second going with the first option.

**Review by tschaffter — APPROVED** [review]
This is terrific work, @rrchai ! I tested the PR and it works well.

**Pull request merged**
