### PR TITLE
feat: Add /assetTypes/{assetType}/assetViews/{assetViewId}/datasets/{datasetId}/files endpoint

### PR DESCRIPTION
**Pull request by andrewelamb**
fixes [fds-770](https://sagebionetworks.jira.com/browse/FDS-770)

### CODE REVIEW

**Comment by andrewelamb** [comment]
@GiaJordan This PR is ready for review, thanks!

**Review by GiaJordan — APPROVED** [review]

**Review by tschaffter — CHANGES_REQUESTED** [review]
Updating VS Code preferences must be done and reviewed in a separate PR.

**Comment by andrewelamb** [comment]
@tschaffter Is that the settings.json file? I think vscode changed that (I didn't manually) I'll change that back.

**Review by tschaffter — APPROVED** [review]
LGTM

**Pull request merged**
