### PR TITLE
feat: Manage container dependency with Docker Compose

### LINKED ISSUE #647: Create a new docker-compose.yml to deploy the Challenge Registry
See:

- [ ] [Using Docker Compose with Nx Monorepo For Multi Apps Development](https://www.codefeetime.com/post/using-docker-compose-with-nx-monorepo-for-multi-apps-development/)
- [x] [A sample to manage multiple Apps in Nx using docker-compose ](https://github.com/DriLLFreAK100/nx-docker-compose-sample)

### LINKED ISSUE #1315: [Bug] Vault docker image not available when starting the app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

The issue happens when starting from a clean environment where even images have been removed. Starting the app then leads to the following issue:

```console
$ nx serve openchallenges-app
...
>  Nx Container  Removing temp folder /tmp/docker-build-push-jiqJpj


> nx run openchallenges-api-gateway:serve-detach

openchallenges-vault Pulling 
openchallenges-vault Error 
Error response from daemon: manifest for sagebionetworks/openchallenges-vault:latest not found: manifest unknown: manifest unknown

 >  NX   ERROR: Something went wrong in run-commands - Command failed: docker/openchallenges/serve-detach.sh openchallenges-api-gateway

   Pass --verbose to see the stacktrace.


> nx run openchallenges-organization-service:build-image-base
```

### Expected behavior

The image `sagebionetworks/openchallenges-vault` should be built as part of the deployment process, then successfully started.

### Anything else?

Rang experienced this issue too when deploying the app on the new EC2 instance.

### Commit ID

eb135fc

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1316: [Story] Build production-ready Docker images for OC
### What projects is this story for?

OpenChallenges

### As a user, I want

As a developer, I want to be able to build production-ready Docker images so that I can test the production version of the stack.

### Description

Review the existing docker images of the OC components and identify changes that are recommended for production deployment. For example, the Spring microservices are started with the command [`start-dev`](https://github.com/Sage-Bionetworks/sage-monorepo/blob/2c6eddc5dd89a8b7315109eb169e57797fe2e658/docker/openchallenges/services/service-registry.yml#L14) that should probably replaced by a production alternative. Also, the Angular app should be built with the production flag (CSR).

### Acceptance criteria

- The Spring microservices start with the production alternative to `start-dev`.
- The Angular app is built for production before being dockerized.

### Tasks

- [x] #1345
- [x] #1346

### Anything else?

- https://gitlab.com/spring-cloud-infrastructure/docker

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### LINKED ISSUE #1318: Add Docker healthcheck for Elasticsearch
Elasticsearch takes a couple of minutes to initialize. This leads the challenge service, which depends on ES, to keep restarting its container. This prevent the app from starting successfully.

### PR DESCRIPTION
**Pull request by tschaffter**
- Fixes #1315
- Fixes #1318
- Fixes #647

## Changelog

- Add the command `openchallenges-build-images` to build all the OC images.
- The tasks `serve` and `serve-detach` no longer:
  - build the images needed to serve the project
  - serve project dependencies
- Remove two projects related to opensearch.

## Future Work

- Build only the images needed to support a given service/app.
  - See [Using the Nx Dependency Graph in Custom Scripts](https://juristr.com/blog/2020/09/use-nx-dep-graph-in-custom-scripts/)

## Preview

Build the images (see section Future Work for improvement):

```console
openchallenges-build-images
```

Start the app and all its dependencies with Docker Compose:

```console
nx serve-detach openchallenges-app
```

> **Note** For now the container of the app is a simple httpd container. We are working on a ticket to dockerize the actual app. This work is not a blocker for this ticket.

Do you want to contribute to one of the components of the stack? Here is how it goes:

Stop the container of the component. E.g. for the app:

```console
docker stop openchallenges-app
```

Start the component in development mode:

```console
nx serve openchallenges-app
```

Voila!

### CODE REVIEW

**Comment by tschaffter** [comment]
## Build all the OC images (4-core EC2)

```console
$ time openchallenges-build-images 

    ✔  nx run openchallenges-app-config-data:build  [local cache]
    ✔  nx run shared-java-util:build  [local cache]
    ✔  nx run openchallenges-kafka-model:build  [local cache]
    ✔  nx run openchallenges-app-config-data:install (4s)
    ✔  nx run openchallenges-kafka-model:install (24s)
    ✔  nx run shared-java-util:install (25s)
    ✔  nx run openchallenges-kafka-admin:build  [local cache]
    ✔  nx run openchallenges-config-server:build-image-base (25s)
    ✔  nx run openchallenges-kafka-admin:install (16s)
    ✔  nx run openchallenges-service-registry:build-image-base (35s)
    ✔  nx run openchallenges-api-gateway:build-image-base (30s)
    ✔  nx run openchallenges-kafka-consumer:build  [local cache]
    ✔  nx run openchallenges-kafka-producer:build  [local cache]
    ✔  nx run openchallenges-kafka-consumer:install (13s)
    ✔  nx run openchallenges-kafka-producer:install (5s)
    ✔  nx run openchallenges-organization-service:build-image-base (36s)
    ✔  nx run openchallenges-config-server:build-image (3s)
    ✔  nx run openchallenges-vault:build-image (4s)
    ✔  nx run openchallenges-service-registry:build-image (3s)
    ✔  nx run openchallenges-challenge-service:build-image-base (25s)
    ✔  nx run openchallenges-postgres:build-image (4s)
    ✔  nx run openchallenges-keycloak:build-image (3s)
    ✔  nx run openchallenges-mariadb:build-image (4s)
    ✔  nx run openchallenges-api-gateway:build-image (3s)
    ✔  nx run openchallenges-organization-service:build-image (3s)
    ✔  nx run openchallenges-challenge-service:build-image (3s)
    ✔  nx run openchallenges-elasticsearch:build-image (4s)
    ✔  nx run openchallenges-api-docs:build-image (4s)
    ✔  nx run openchallenges-zipkin:build-image (4s)
    ✔  nx run openchallenges-kafka:build-image (4s)
    ✔  nx run openchallenges-mongo:build-image (5s)
    ✔  nx run openchallenges-auth-service:build-image (26s)
    ✔  nx run openchallenges-core-service:build-image (30s)
    ✔  nx run openchallenges-challenge-to-elasticsearch-service:build-image (21s)
    ✔  nx run openchallenges-user-service:build-image (43s)
    ✔  nx run openchallenges-kaggle-to-kafka-service:build-image (21s)

real    2m27.678s
user    1m21.103s
sys     0m18.354s
```

**Review by rrchai — APPROVED** [review]
Works good as the new workflow

**Review by vpchung — APPROVED** [review]
LGTM.

Sidenote: I did have to source `dev-env.sh` first before building the images.

**Comment by tschaffter** [comment]
> Sidenote: I did have to source dev-env.sh first before building the images.

It is because the file `dev-env.sh` is not source after a git operation like `git checkout`. This is a quality of life improvement we can make in another PR.

**Pull request merged**
