### PR TITLE
fix(ui): add biomedical-ness to landing page graphic

### LINKED ISSUE #1836: [Enhancement] Add biomedical "zing" to graphics used on Home page
## Sage Design feedback

Current home page graphic:

Image

At a quick first glance, it is not clear that this is a website dedicated to _biomedical_ challenges, at least, not until some text is read.  

Consider adding a DNA helix or some other type of biomedical-related graphics/image to the main graphic.

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #1836 

## Changelog
* update magnifying glass graphic (other suggestions posted [here](https://github.com/Sage-Bionetworks/sage-monorepo/issues/1836#issuecomment-1734268053) and [here](https://sagebionetworks.slack.com/archives/C0262MYRJ2H/p1695747817686039))

## Preview
Screenshot 2023-09-26 at 8 44 56 PM

### CODE REVIEW

**Comment by vpchung** [comment]
I also played around with the text formatting, splitting the paragraph into two, where the first sentence could act as our slogan/catchphrase.  Let me know what you think, or whether we should stick with the original proposed idea!

## Version A
Same text size for both paragraphs:
Screenshot 2023-09-26 at 4 30 38 PM

## Version B
Smaller text size for the second paragraph:
Screenshot 2023-09-26 at 4 30 49 PM

**Review by rrchai — APPROVED** [review]
The new image looks great! Thanks.

For the paragraphs splitting, I prefer version A to use the same size. Also, it might seem better if there are no that much space after "more" (maybe squeeze it into one line?).

**Review by tschaffter — COMMENTED** [review]
The latest version of the main illustration is splendid! :sparkles:

I vote for Option A as the smaller text is too small for the top section of the home page.

I'm not sure about is the change from "It empowers..." to "Empowering...". I would expect a subject in this sentence instead of inserting a "headline" after a sentence that has a subject.

**Comment by vpchung** [comment]
Thank you both!  Here is the latest iteration:

Screenshot 2023-09-27 at 9 08 49 AM

Again, we don't have to go with the paragraph splitting; just thought I'd throw that idea out.  Here is the original:

Screenshot 2023-09-27 at 9 10 37 AM

**Comment by tschaffter** [comment]
@vpchung What about "OC empowers..." as a mean to introduce the acronym?

**Pull request merged**
