### PR TITLE
feat: Filter challenges by organization

### LINKED ISSUE #1035: [Story] Filter challenges by organization
Enable to filter challenges by organization.

## Tasks

- [x] Update API description to filter challenges by contributors
- [x] Update the challenge service to filter challenges by contributors
- [ ] Update the client library for Angular
- [ ] #1402
- [ ] #1421

### LINKED ISSUE #1402: Update the web app to filter challenges by orgs
We already have a UI for this filter. The goal of this ticket is to connect this UI to the new backend feature that enables to filter challenges by organization (see #1401).

### LINKED ISSUE #1421: [Story] Enable to search org by searchTerm in the dropdown widget
### What projects is this story for?

OpenChallenges

### Description

The current search field and dropdown on the widget come together using the existing component from primeng ([MultiSelect](https://primeng.org/multiselect)). The search field will only filter the label of options. We would like to utilize the search field to filter the organizations by `searchTerm`.

As @tschaffter purposed, the widget should behave like below:
- The user starts typing in the widget search field. 400 ms after the user stopped typing, a request is sent to the org service to find orgs that match the search terms.
- The widget receives a list of orgs based on the search terms. The list of orgs in the widget is updated.

### Acceptance criteria

- the org can be filtered by the search term in the dropdown

### Tasks

- #1423 

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

### PR DESCRIPTION
**Pull request by tschaffter**
- Closes #1035 
- Closes #1402
- Closes #1421

## TODO

- Challenge Search
  - Filter by Organization
    - [x] Get the org avatar URL using the new `ImageService.getImage()` (@rrchai )
    - [x] Fix the bug shown in the GIF below (@rrchai )

## Changelog

- #1401
- #1420
- #1423

## Preview

Filter challenges by org

Recording 2023-06-13 at 09 37 28

### CODE REVIEW

**Comment by tschaffter** [comment]
@rrchai I merged `main` into this feature branch, which adds DREAM as a contributor of more challenges.

**Comment by tschaffter** [comment]
Target deadline: June 12

**Comment by tschaffter** [comment]
@rrchai Something probably broken when I merged the conflict. Also, the logo of the organizations does not show in the widget because I commented out the avatar property. This property needs to be restored and the value should come from `ImageService.getImage()` as discussed on Slack.

Recording 2023-06-05 at 15 05 02

**Comment by tschaffter** [comment]
CONFIRMED: Challenges can be filtered by one or more organizations.

```
GET {{basePath}}/challenges?organizations=1

HTTP/1.1 200
{
  "number": 0,
  "size": 100,
  "totalElements": 47,
  "totalPages": 1,
  "hasNext": false,
  "hasPrevious": false,
  "challenges": [
    {
      "id": 11,
      "slug": "broad-dream-gene-essentiality-prediction",
      "name": "Broad-DREAM Gene Essentiality Prediction",
      "headline": "",
      "description": "The goal of this project is to use a crowd-based competition to develop predictive models that can infer gene dependency scores in cancer cells (genes that are essential to cancer cell viability when suppressed) using features of those cell lines. An additional goal is to find a small set of biomarkers (gene expression, copy number, and mutation features) that can best predict a single gene or set of genes.",
      "status": "completed",
      "difficulty": "intermediate",
      "platform": {
        "id": 1,
        "slug": "synapse",
        "name": "Synapse"
      },
      "websiteUrl": "https://www.synapse.org/#!Synapse:syn2384331",
      "avatarUrl": null,
      "incentives": [
        "publication",
        "speaking_engagement"
      ],
      "submissionTypes": [
        "prediction_file"
      ],
      "inputDataTypes": [],
      "startDate": "2014-06-02",
      "endDate": "2014-09-29",
      "starredCount": 0,
      "createdAt": "2023-06-06T01:54:52Z",
      "updatedAt": "2023-06-06T01:54:52Z"
    },
    {
      "id": 55,
      "slug": "cough-diagnostic-algorithm-for-tuberculosis",
      "name": "COugh Diagnostic Algorithm for Tuberculosis",
...
```

**Comment by rrchai** [comment]
The avatars of orgs in dropdown are retrieved using imageService. I borrow @tschaffter code used in org-search page. I notice there are a little bit delay (2-3s) to get all orgs. For example, when the challenge-search page is loaded, users will not see options in the organization dropdown until the orgs including avatars are all queried in 2-3s.
It's not a big deal now, but may cause longer delays with more orgs added into the database in the future.

**Comment by rrchai** [comment]
More descriptions on the unexpected behavior reported by @tschaffter (shown in gif above):

When select the any option in organization dropdown, it will also select the rest of options. After troubleshooting with @tschaffter , we found the reason is because the angular client for organization service is not update-to-date. It's actually missing some chunks of code for `orgId`, which results in that the `orgId` of all organizations are returned as `null`. Since the dropdown is using `orgId` as filter value, selecting any of options (`null`) will select all options.

To resolve this issue, simply updating angular client for organization service with below code:

```console
nx openapi-generate openchallenges-organization-service
```

---
Some steps we did while trying to find the reason:
1. checked the type of orgId in data-models, `Organization.yaml`
2. found the mismatched types of orgId in .sql file -> change the string orgId to integer
3. checked the `orgId` type in `OrganizationDto.java`, `OrganizationEntity.java` (whether it's `Long` type
4. checked the `orgId` type in schemas, `V1.0.0__create_tables.sql`
5. debugged organization service in dev mode: 
    - launch the service in dev mode by `nx serve openchallenges-organization-service`
    - print out entity in `OrganizationService.java` by adding `LOG.info("{}", org}`
    - see the log by sending a request in Swagger

---
Steps to update organization data and organization service, if changes:
1. stop and **remove** organization service container (click "remove" in docker extension)
2. rebuild the image by `nx build-image openchallenges-organization-service`
3. restart the container: `nx serve-detach openchallenges-app`

**Comment by rrchai** [comment]
@tschaffter The issues in this pr should be fixed.

**Comment by tschaffter** [comment]
> For example, when the challenge-search page is loaded, users will not see options in the organization dropdown until the orgs including avatars are all queried in 2-3s.

What is the size in pixel of the org logo displayed in the dropdown? Is it smaller than the 100x100 px images requested from the image service? Downloading the image at the right size - after modified the image service to allow this size - should lead to an improvement but won't solve the overall performance issue discussed previously.

**Comment by tschaffter** [comment]
> To resolve this issue, simply updating angular client for organization service with below code:
> nx openapi-generate openchallenges-organization-service

@rrchai This command update the organization (micro)service, not the API client for Angular.

**Comment by rrchai** [comment]
> What is the size in pixel of the org logo displayed in the dropdown? Is it smaller than the 100x100 px images requested from the image service? 

@tschaffter I used 100px, which is the smallest option from `ImageHeight`.

>This command update the organization (micro)service, not the API client for Angular.

Ah, right.  Thanks for clarification.

**Comment by tschaffter** [comment]
> @tschaffter I used 100px, which is the smallest option from ImageHeight.

But what is the size of the *displayed* images in the dropdown?

**Comment by rrchai** [comment]
> What is the size of the displayed images in the dropdown?

32px

**Comment by tschaffter** [comment]
@rrchai The PR shown above this comment will enable the app to request 32x32 logos.

**Comment by tschaffter** [comment]
I can't technically approve the PR because I created this feature branch, which we used to group multiple features branches together before merging to `main`. I've reviewed this feature that includes the latest contributions from @rrchai and approve it.

**Pull request merged**
