### PR TITLE
fix(openchallenges): restructure docs site

### LINKED ISSUE #2430: [Docs] Structure Sage Monorepo docs
### What product(s) is this documentation issue for?

Sage Monorepo

### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Description

We now have a solution to render markdown files so that they are displayed on GitHub pages.

This solution requires us to structure the documentation in a way that is intuitive to the users of the doc.

The goal of this ticket is to come up with an initial structure, potentially with placeholder pages and sections, that we can then fill in. In particular, this work should results in clear guidelines on how to write new documentation content, e.g. how to format links, where to place markdown files, etc.

### Is there a specific documentation page you are reporting?

_No response_

### Anything else?

There are three places that may include relevant documentation that we may want to include in the doc site:

- Workspace-level README
- Project-level READMEs
- Pages in the `docs/` folder

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #2430 

## Changelog

* Update categories to:
   * Home: overview of the monorepo, current supported tools/products
   * Getting Started: introduces the technologies involved and how to setup locally/remotely
   * Tutorials: walks user through how to develop, organized by product
   * Developers Guide: walks user through how to maintain and update the monorepo
   * Reference: list of classes/APIs/microservices, organized by product

## To test locally

1. Install mkdocs, mkdocs-material, and termynal, ideally in a virtual environment, e.g.

   ```
   conda create -n docs python=3.12
   conda activate docs
   pip install mkdocs mkdocs-material termynal
   ```

2. Checkout this branch, then start the server:

   ```
   mkdocs serve
   ```

   This will serve the documentation on http://127.0.0.1:8000. If you get an error about the port already being used, stop the affected container:

   ```
   workspace-docker-stop
   ```

Once done, stop the server with Ctrl + C

## Preview

[More recent screenshots found in comment below](https://github.com/Sage-Bionetworks/sage-monorepo/pull/2441#issuecomment-1922385439)

**Home page**
Screenshot 2024-01-23 at 3 10 49 PM

**Getting Started**
Screenshot 2024-01-23 at 3 11 01 PM

**Tutorials**
Screenshot 2024-01-23 at 3 11 07 PM

**Developers Guide**
Screenshot 2024-01-23 at 3 11 14 PM

**Reference**
Screenshot 2024-01-23 at 3 11 20 PM

### CODE REVIEW

**Comment by tschaffter** [comment]
Home page:
- the logos don't render in the markdown preview on GH
- the logos take a lot of space, including in the source of the file
  - replace by a table that include info about the project and link to the product space on the doc site?
- Tutorials
  - Split by programming languages or project type
  - This should contribute to developing reusable components instead of project-specific component
    - E.g. Creating a REST API in Python should be the same for Schematic or OpenChallenges
  - Types of projects:
    - Java:
      - library
      - REST API
    - Python
      - REST API
    - Angular
      - App
      - library
      - API client for Angular (is a library)
    - R
      - library
   - Docker-based project (e.g. `openchallenges-mariadb`)

**Comment by tschaffter** [comment]
@vpchung The proposed structure is already a nice improvement on the initial version. Feel free to use my feedback as you see fit and then merge when you are satisfied. I expect the structure of the docs to become clearer as we start curating its content.

**Comment by vpchung** [comment]
> the logos don't render in the markdown preview on GH

I did not touch the main README for the repo, so no changes should be seen there.

> replace by a table that include info about the project and link to the product space on the doc site?

> Split by programming languages or project type

Sounds good.

**Comment by vpchung** [comment]
Feedback has been implemented:

Screenshot 2024-02-01 at 2 26 40 PM

Screenshot 2024-02-01 at 2 26 52 PM

**Comment by vpchung** [comment]
> then merge when you are satisfied

@tschaffter I don't have the permission to force-merge without an approval.  We can merge this after your return!

**Comment by tschaffter** [comment]
@vpchung How can this PR be tested?

**Comment by vpchung** [comment]
Thanks, added notes above to the description.

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
