### PR TITLE
feat(data): Refactor SQL files for dumping data into openchallenges-db

### LINKED ISSUE #2047: Explore LOAD LOCAL INFILE for inserting data?
## Motivation

Our current process of updating the database tables is:

1. export the Google Sheets as CSV
2. run a Python script that will clean up the data and reformat it to something SQL will accept, e.g.

   **Before**
   ```python
           id                                          name                                          slug  ...            createdAt            updatedAt _validSlug
   0        1      Network Topology and Parameter Inference      network-topology-and-parameter-inference  ...  2023-06-23 00:00:00  2023-08-09 08:42:17       True
   1        2                       Breast Cancer Prognosis                       breast-cancer-prognosis  ...  2023-06-23 00:00:00  2023-07-26 19:47:13       True
   2        3          Phil Bowen ALS Prediction Prize4Life          phil-bowen-als-prediction-prize4life  ...  2023-06-23 00:00:00  2023-07-26 19:47:15       True
   ..     ...                                           ...                                           ...  ...                  ...                  ...        ...
   ```

   **After**
   ```txt
   (
       1,
       'network-topology-and-parameter-inference',
       'Network Topology and Parameter Inference',
       '',
       'Participants are asked to develop and/or apply optimization methods, including the selection of the most informative experiments, to accurately estimate parameters and
    predict outcomes of perturbations in Systems Biology models.',
       'https://www.synapse.org/#!Synapse:syn2821735',
       'completed',
       'intermediate',
       '1.0',
       '',
       '2012-06-01',
       '2012-10-01',
       '2023-06-23 00:00:00',
       '2023-08-09 08:42:17'
     ),
     (
       2,
       ...
   ```

3. copy-paste the results to the SQL file in challenge-service or organization-service

This ticket will focus on step 3, in particular: rather than continuing to edit the SQL file(s), we can import the data into the tables directly from flat file(s).  This can be achieved by refactoring the current SQL script to utilize the `LOAD LOCAL INFILE` function, e.g. from

```
INSERT INTO challenge (
    id,
    slug,
    name,
    headline,
    description,
    website_url,
    status,
    difficulty,
    platform_id,
    doi,
    start_date,
    end_date,
    created_at,
    updated_at
  )
VALUES (
  ...
);
```

to

```
LOAD DATA INFILE 'challenges.txt' INTO TABLE challenge
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
```

## Things to consider

* `LOCAL` works only if the server and your client both have been configured to permit it. @tschaffter - here is a writeup on the [security considerations for LOAD DATA LOCAL](https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html)
   * by default, `local_infile` is disabled on the server; we will need to update this if we want to move forward with this refactor
   * by default, the client library in MySQL binary distributions is compiled with ENABLED_LOCAL_INFILE disabled; we will additionally need to reconfigure the client with [ENABLED_LOCAL_INFILE](https://dev.mysql.com/doc/refman/8.0/en/source-configuration-options.html#option_cmake_enabled_local_infile) enabled

### LINKED ISSUE #2169: [Feature] <Add Research to the People as organization>
### What product(s) is this feature for?

_No response_

### Description

I have added some hackathons from this new organization to the OpenChallenges Data file 
this is their logo. Would be great to add them to the Organization's list.
Thank you @vpchung!

### Anything else?

Screen Shot 2023-09-27 at 9 09 46 PM

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #2176: [Data] Add at least one challenge hosted on platforms with `challengeCount` = 0
This ticket is related to #2144

Because we'll be displaying platform logos on the homepage, we should also ideally have _at least_ one challenge of each of those listed platforms. At this time, we don't have any annotated challenges from Codalab, Codabench,  ~~OpenML, or Papers With Code.~~

### PR DESCRIPTION
**Pull request by vpchung**
Fixes #2047 ; goes hand-in-hand with #2114

Due to downloading the OC Data as CSVs in order to generate the flat files, this also fixes #2169 and fixes #2176 

## Changelog
* Enable `local_infile` feature in mariadb server
* Refactor *data.sql files to load data directly from flat files
* Update database with snapshot date of 2023-09-28
   * Added challenges from CAGI, CodaBench, and CodaLab
   * Added new organizations, incl. Research to the People
   * General updates to challenges and organizations

## Preview
Screenshot 2023-09-29 at 5 14 21 AM

### CODE REVIEW

**Comment by vpchung** [comment]
Hmm, looks like I'm also not able to generate the cards on the home page either:

Screenshot 2023-09-29 at 10 41 09 AM

Not sure if this is related to the "Other" facet mentioned earlier... Reverting this back to drafts.

**Comment by vpchung** [comment]
> everything worked as expected except the Other option for the Platform facet.

Whoops, the error also reproduces when selecting `Upcoming` from Status, `Starting Soon` from Category, and `2023`, `2022`, or `2017 - 2021` from Challenge Year.

**Comment by vpchung** [comment]
After playing around with web app, I think the issue stems from one challenge: 

### Jan2024: Rare Disease AI Hackathon

I noticed that using any search terms related to this challenge, e.g. `rare`, `disease`, would also give us the error; hence why I think this particular challenge is the issue. Plus, it has a status = `upcoming` and platform = `other` so that tracks with the patterns mentioned above.

**Comment by vpchung** [comment]
FOUND THE 🐛 !!  It was actually not just the hackathon that caused the issue, but any challenges that had `doker` as its submission type (instead of `container_image`.  Updating these values has fixed the issue 🎉 

Data contributors have been notified of this as to help prevent this in the future.

**Review by tschaffter — APPROVED** [review]

**Pull request merged**
