### PR TITLE
feat: Add ACM certificate for OC prod DNS

### PR DESCRIPTION
**Pull request by tschaffter**
Contributes to #1898

## Changelog

- Add a ACM certificate to the stack `cnb-dev` for all OC DNS names

## TODO

- [ ] Manually delete the old certificate with ID `b1c70716-8f19-4d06-9737-1dd34f56afc4`

## Notes

- Once applied (`cdktf deploy cnb-dev`), the existing certificate for `dev.openchallenges.io` will be removed according to the diff output shown below.

## Preview

Output of `cdktf diff cnb-dev`

```console
cnb-dev  Terraform used the selected providers to generate the following execution
         plan. Resource actions are indicated with the following symbols:
         +/- create replacement and then destroy

         Terraform will perform the following actions:
cnb-dev    # aws_acm_certificate.dns_openchallenges_cert_42540034 (dns/openchallenges_cert) must be replaced
         +/- resource "aws_acm_certificate" "dns_openchallenges_cert_42540034" {
               ~ arn                       = "arn:aws:acm:us-east-1:384625883722:certificate/b1c70716-8f19-4d06-9737-1dd34f56afc4" -> (known after apply)
               ~ domain_name               = "dev.openchallenges.io" -> "openchallenges.io" # forces replacement
               ~ domain_validation_options = [
                   - {
                       - domain_name           = "dev.openchallenges.io"
                       - resource_record_name  = "_8c411fb9dbec6c9424a1173ab736b81e.dev.openchallenges.io."
                       - resource_record_type  = "CNAME"
                       - resource_record_value = "_06aa7293b30f9eda06f0f47165ff7632.zsqxqtfsbl.acm-validations.aws."
                     },
                   + {
                       + domain_name           = "*.openchallenges.io"
                       + resource_record_name  = (known after apply)
                       + resource_record_type  = (known after apply)
                       + resource_record_value = (known after apply)
                     },
                   + {
                       + domain_name           = "openchallenges.io"
                       + resource_record_name  = (known after apply)
                       + resource_record_type  = (known after apply)
                       + resource_record_value = (known after apply)
                     },
                 ]
               ~ id                        = "arn:aws:acm:us-east-1:384625883722:certificate/b1c70716-8f19-4d06-9737-1dd34f56afc4" -> (known after apply)
               ~ key_algorithm             = "RSA_2048" -> (known after apply)
               ~ not_after                 = "2024-08-10T23:59:59Z" -> (known after apply)
               ~ not_before                = "2023-07-13T00:00:00Z" -> (known after apply)
               ~ pending_renewal           = false -> (known after apply)
               ~ renewal_eligibility       = "ELIGIBLE" -> (known after apply)
               ~ renewal_summary           = [] -> (known after apply)
               ~ status                    = "ISSUED" -> (known after apply)
               ~ subject_alternative_names = [ # forces replacement
                   - "dev.openchallenges.io",
                   + "*.openchallenges.io",
                   + "openchallenges.io",
                 ]
                 tags                      = {
                     "CostCenter" = "ITCR / 101600"
                     "Name"       = "cnb-dev-openchallenges-cert"
                     "OwnerEmail" = "thomas.schaffter@sagebionetworks.org"
                 }
               ~ type                      = "AMAZON_ISSUED" -> (known after apply)
               ~ validation_emails         = [] -> (known after apply)
                 # (2 unchanged attributes hidden)

               - options {
                   - certificate_transparency_logging_preference = "ENABLED" -> null
                 }

               - validation_option { # forces replacement
                   - domain_name       = "dev.openchallenges.io" -> null
                   - validation_domain = "openchallenges.io" -> null
                 }
               + validation_option { # forces replacement
                   + domain_name       = "openchallenges.io"
                   + validation_domain = "openchallenges.io"
                 }
             }

         Plan: 1 to add, 0 to change, 1 to destroy.
         
         Changes to Outputs:
           - cert_arn                = "arn:aws:acm:us-east-1:384625883722:certificate/b1c70716-8f19-4d06-9737-1dd34f56afc4" -> null
           + openchallenges_cert_arn = (known after apply)
```

### CODE REVIEW

**Comment by tschaffter** [comment]
@xschildw Do we need the two certificates or the new one could be used for `dev.openchallenges.io` since it covers `*.openchallenges.io`?

**Comment by xschildw** [comment]
Just one.

**Comment by tschaffter** [comment]
I have updated the PR. Once you have approved the PR, I will apply the changes.

**Review by xschildw — APPROVED** [review]
LGTM

**Comment by tschaffter** [comment]
The deployment of the stack fail because the certificate is used.

image

At this point I don't want to destroy the stack so I'll find a workaround.

**Comment by tschaffter** [comment]
Tell TF to forget about the existing certificate that it can not destroy because it's used:

```console
vscode@34f14f659357:/workspaces/sage-monorepo/apps/openchallenges/infra/cdktf.out/stacks/cnb-dev$ terraform state list
aws_acm_certificate.dns_openchallenges_cert_42540034
aws_route53_zone.dns_openchallenges_zone_EBE506EC

vscode@34f14f659357:/workspaces/sage-monorepo/apps/openchallenges/infra/cdktf.out/stacks/cnb-dev$ terraform state rm 'aws_acm_certificate.dns_openchallenges_cert_42540034'
Removed aws_acm_certificate.dns_openchallenges_cert_42540034
Successfully removed 1 resource instance(s).
```

**Comment by tschaffter** [comment]
The certificate has been validated by @xschildw

**Pull request merged**
